### ISSUE TITLE
Submit to MELPA

### ISSUE THREAD

**Issue by bgamari** [tibbe/cmm-mode#2]
[MELPA](https://github.com/milkypostman/melpa) is a widely used repository for emacs lisp packages. It would be nice to submit this for inclusion. I would be happy to manage this if you would prefer.

**Comment by tibbe** [comment]
Please go ahead.

**Comment by supersven** [comment]
Looks like this is done : https://melpa.org/#/cmm-mode 😃

**Comment by bgamari** [comment]
Horray!
